# 图片验证码Redis有效期， 单位：秒
IMAGE_CODE_REDIS_EXPIRES = 300

# 短信验证码Redis有效期，单位：秒
SMS_CODE_REDIS_EXPIRES = 300

SEND_SMS_CODE_INTERVAL = 60

SEND_SMS_TOKEN_EXPIRES = 300


SET_PASSWORD_TOKEN_EXPIRES = 300

SAVE_QQ_USER_TOKEN_EXPIRES = 300

EMAIL_VERIFY_TOKEN_EXPIRES = 300

USER_ADDRESS_COUNTS_LIMIT = 300

HOT_SKUS_COUNT_LIMIT = 20

USER_BROWSING_HISTORY_COUNTS_LIMIT = 60